version: '3'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - HOST_DATA_PATH=/app/data/processed
    ports:
      - "8000:8000"
    volumes:
      - ${HOST_DATA_PATH}:/app/data/processed